In [123]:
import numpy as np
import keras
from keras.models import Model
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adadelta , RMSprop
import matplotlib.pyplot as plt 
%matplotlib inline


In [59]:
#Initilize Model
model = Sequential()
#Encoder
model.add(Dense(1024,activation="relu",input_shape=(1024,)))
model.add(Dense(256,activation="relu"))

#Encoded
model.add(Dense(128,activation="relu",name="encoded_result"))

#Decoder
model.add(Dense(256,activation="relu"))
model.add(Dense(512,activation="relu"))
model.add(Dense(1024,activation="relu"))

In [16]:
#Initialize Hyperparameter
batch_size = 32
epoch = 30


In [41]:
#Loading Data
import json

In [42]:
with open('16ksongs.json',encoding='utf-8') as f:
    data = json.load(f)


In [43]:
for record in data:
    newList = []
    record['waveMax'] = record['waveMax'] [1:][:-1]
    record['waveMin'] = record['waveMin'] [1:][:-1]
    waveMax = record['waveMax'].split(",")
    waveMin = record['waveMin'].split(",")
    if len(waveMax) == 1025:
        waveMax.pop()
        waveMin.pop()
    for index, value in enumerate(waveMax):
        value = (float(waveMin[index])+float(waveMax[index]) )
        value /= 2
        newList.append(value)
    record['wave'] = np.array(newList)
#     print(record['name'])
    
all_data= data.pop(0)['wave']

for item in data:
    all_data = np.vstack((all_data , item['wave']))


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1024 and the array at index 1 has size 48

In [55]:
all_data.shape

(15793, 1024)

In [60]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_20 (Dense)             (None, 1024)              1049600   
_________________________________________________________________
dense_21 (Dense)             (None, 256)               262400    
_________________________________________________________________
encoded_result (Dense)       (None, 128)               32896     
_________________________________________________________________
dense_22 (Dense)             (None, 256)               33024     
_________________________________________________________________
dense_23 (Dense)             (None, 512)               131584    
_________________________________________________________________
dense_24 (Dense)             (None, 1024)              525312    
Total params: 2,034,816
Trainable params: 2,034,816
Non-trainable params: 0
_________________________________________________________________


In [68]:
model.compile(optimizer='adadelta', loss='binary_crossentropy')


In [71]:
model.fit(all_data,all_data,epochs=100,batch_size=32,validation_data=(all_data,all_data))

Train on 15793 samples, validate on 15793 samples
Epoch 1/100
15793/15793 [==============================] - 5s 301us/step - loss: -5.4619 - val_loss: -5.4765
Epoch 2/100
15793/15793 [==============================] - 4s 281us/step - loss: -5.4625 - val_loss: -5.4582
Epoch 3/100
15793/15793 [==============================] - 4s 281us/step - loss: -5.6030 - val_loss: -5.7141
Epoch 4/100
15793/15793 [==============================] - 4s 282us/step - loss: -5.8499 - val_loss: -6.0248
Epoch 5/100
15793/15793 [==============================] - 4s 281us/step - loss: -6.0846 - val_loss: -6.0347
Epoch 6/100
15793/15793 [==============================] - 4s 281us/step - loss: -5.9807 - val_loss: -5.8715
Epoch 7/100
15793/15793 [==============================] - 5s 289us/step - loss: -5.8523 - val_loss: -5.8390
Epoch 8/100
15793/15793 [==============================] - 4s 285us/step - loss: -5.7543 - val_loss: -5.7322
Epoch 9/100
15793/15793 [==============================] - 5s 292us/step - los

15793/15793 [==============================] - 5s 332us/step - loss: -5.3515 - val_loss: -5.3515
Epoch 76/100
15793/15793 [==============================] - 5s 339us/step - loss: -5.3515 - val_loss: -5.3515
Epoch 77/100
15793/15793 [==============================] - 5s 343us/step - loss: -5.3515 - val_loss: -5.3515
Epoch 78/100
15793/15793 [==============================] - 5s 313us/step - loss: -5.3515 - val_loss: -5.3515
Epoch 79/100
15793/15793 [==============================] - 5s 290us/step - loss: -5.3515 - val_loss: -5.3515
Epoch 80/100
15793/15793 [==============================] - 5s 295us/step - loss: -5.3515 - val_loss: -5.3515
Epoch 81/100
15793/15793 [==============================] - 5s 308us/step - loss: -5.3515 - val_loss: -5.3515
Epoch 82/100
15793/15793 [==============================] - 5s 322us/step - loss: -5.3515 - val_loss: -5.3515
Epoch 83/100
15793/15793 [==============================] - 5s 322us/step - loss: -5.3515 - val_loss: -5.3515
Epoch 84/100
15793/1579

In [72]:
model.save('punton_keras.h5')


In [84]:
#Load song to test
with open('songs.json',encoding='utf-8') as f:
    test = json.load(f)


In [85]:
for record in test:
    newList = []
    record['waveMax'] = record['waveMax'] [1:][:-1]
    record['waveMin'] = record['waveMin'] [1:][:-1]
    waveMax = record['waveMax'].split(",")
    waveMin = record['waveMin'].split(",")
    if len(waveMax) == 1025:
        waveMax.pop()
        waveMin.pop()
    for index, value in enumerate(waveMax):
        value = (float(waveMin[index])+float(waveMax[index]) )
        value /= 2
        newList.append(value)
    record['wave'] = np.array(newList)
#     print(record['name'])
    
test_song = data.pop(0)['wave']

for item in test:
    test_song = np.vstack((test_song , item['wave']))


In [86]:
test_song

array([[ 0. ,  1. ,  0. , ..., -1. , -2. ,  0. ],
       [-0.5, -2.5, -0.5, ...,  0. ,  0. ,  0. ],
       [ 0. , -0.5,  0.5, ...,  0. ,  0. ,  0. ],
       ...,
       [ 0. , -0.5,  0.5, ...,  0. ,  0. ,  0. ],
       [ 0. , -1. , -0.5, ..., -0.5, -0.5,  0. ],
       [ 0. , -0.5,  3.5, ...,  0. ,  0. ,  0. ]])

In [118]:
result = model.predict(test_song)

In [109]:
test_song[3]

array([ 0.,  2., -1., ...,  0.,  0.,  0.])

In [126]:
intermediate_layer_model = Sequential()
middle_layer = 'encoded_result'
intermediate_layer_model = Model(inputs=model.input,
                                 outputs=model.get_layer(middle_layer).output)
intermediate_output = intermediate_layer_model.predict(test_song)

In [127]:
intermediate_output

array([[   0.    ,  983.2123,    0.    , ...,    0.    , 1182.421 ,
        1069.9945],
       [   0.    , 2035.8523,    0.    , ...,    0.    , 2425.7837,
        2192.6753],
       [   0.    ,  997.5575,    0.    , ...,    0.    , 1186.1327,
        1076.0348],
       ...,
       [   0.    , 1075.3263,    0.    , ...,    0.    , 1279.5514,
        1161.4053],
       [   0.    , 3086.95  ,    0.    , ...,    0.    , 3714.0874,
        3360.8699],
       [   0.    , 2733.453 ,    0.    , ...,    0.    , 3278.7993,
        2969.6372]], dtype=float32)